framework:
    workflows:
        prime_performance:
            type: 'state_machine'
            supports: 'App\Entity\PrimePerformance'
            marking_store:
                type: 'method'
                property: 'status'
            initial_marking: 'draft'
            places:
                - 'draft'
                - 'submitted'
                - 'service_validated'
                - 'division_validated'
            transitions:
                submit:
                    from: 'draft'
                    to: 'submitted'
                service_validate:
                    from: 'submitted'
                    to: 'service_validated'
                division_validate:
                    from: 'service_validated'
                    to: 'division_validated'
                retour_gestionnaire:
                    from: 'submitted'
                    to: 'draft'
                retour_service:
                    from: 'service_validated'
                    to: 'submitted'